# Generated by Django 4.1.7 on 2023-06-21 12:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Booker's name", max_length=255)),
                (
                    "no_of_quest",
                    models.SmallIntegerField(
                        help_text="Number of guest",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Number of guest must be greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "booking_date",
                    models.DateField(
                        default=datetime.date.today, help_text="Booking date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Title", max_length=255, unique=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="Price",
                        max_digits=10,
                    ),
                ),
                ("inventory", models.SmallIntegerField(help_text="Inventory")),
            ],
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
